name: app-ci-develop

on:
  pull_request:
    branches:
      - 'develop/**'
      - 'develop'
    paths:
      - 'src/app/demo1/**'

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/app/demo1
            src/tools
          sparse-checkout-cone-mode: false

