name: app-ci-develop

on:
  pull_request:
    branches:
      - 'develop/**'
      - 'develop'
    paths:
      - 'src/app/demo1/**'
#    types: [closed]

jobs:

  build:

    runs-on: ubuntu-22.04
#    if: github.event.pull_request.merged == true

    steps:

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/app/demo1
            src/tools
          sparse-checkout-cone-mode: false

      - name: Move files to root
        run: |
          ls -lah src
          ls -lah src/app
          shopt -s dotglob
          mv src temp
          mv temp/app/demo1/* .
          echo 'aaa'
          mkdir ../../tools
          ls -lah ../
          echo 'bbb'
          ls -lah ../taketake
          mv temp/tools/* ../../tools
          rm -rf temp
          ls -lah
          pwd
